---
title: "Group_by and summarize"
output: github_document
---

```{r, message = FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  fig.width = 6,
  fig.height = 6,
  out.width = "90%"
)
```


```{r}
weather_df =  
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>%
  select(name, id, everything())
```

## group_by()

```{r}
weather_df %>% 
  group_by(name)

```

## count some things

```{r}
weather_df %>% 
  group_by(name) %>% 
  summarise(n_obs = n())

weather_df %>% 
  count(name)


```

It's nice that summarise produces a data frame

table() doesn't, that is bad.

## two-by-two table

```{r}
weather_df %>% 
  janitor::tabyl(month, name)
```

## More general summaries

Let's count take means, look at SDs ...

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarise(
    n_obs = n(),
    mean_tmax = mean(tmax, na.rm = TRUE),
    median_tmax = median(tmax, na.rm = TRUE),
    sd_tmax = sd(tmax, na.rm = TRUE)
  ) %>% 
  ggplot(aes(x = month, y = mean_tmax, color = name)) +
  geom_point() +
  geom_line()
```

Formatting table outputs

```{r}
weather_df %>% 
  group_by(name) %>% 
  summarise(
    n_obs = n(),
    mean_tmax = mean(tmax, na.rm = TRUE)
  ) %>% 
  knitr::kable(digits = 2)
```


## grouped `mutate`

```{r}
weather_df %>% 
  mutate(
    mean_tmax = mean(tmax, na.rm = TRUE)
  )

weather_df %>% 
  group_by(name) %>% 
  mutate(
    mean_tmax = mean(tmax, na.rm = TRUE),
    centered_tmax = tmax - mean_tmax
  ) %>% 
  ggplot(aes(x = date, y = centered_tmax, color = name)) +
  geom_point()
```


```{r}
weather_df %>% 
  group_by(name) %>% 
  mutate(
    tmax_rank = min_rank(desc(tmax))
  ) %>% 
  filter(tmax_rank < 2)
```

Lagged variables(find data one or n rows lagged)

```{r}
weather_df %>% 
  group_by(name) %>% 
  mutate(
    lagged_tmax = lag(tmax, n = 1),
    tmax_diff = tmax - lagged_tmax
  ) %>% 
  summarise(diff_sd = sd(tmax_diff, na.rm = TRUE))
```



## Limitations

What if my "summary" is linear model ...

you cannot do `lm` in `summarise`

```{r}
weather_df %>% 
  group_by(name) %>% 
  summarise(cor_tmin_tmax = cor(tmin, tmax, use = "complete"))

weather_df %>% 
  filter(name == "CentralPark_NY") %>% 
  lm(tmax ~ tmin, data = .)

```

