---
title: "ggplot_2"
output: github_document
---

```{r}
library(tidyverse)
library(viridis)
library(ggridges)
knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  fig.width = 6,
  fig.height = 6,
  out.width = "90%"
)

```


```{r}
weather_df <- 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

## Start with a familiar one

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .3) +
  labs(
    title = "Temperature at three stations",
    x = "Minimum daily temp(C)",
    y = "Maximum daily temp(C)",
    caption = "Data from rnoaa package with three stations"
  )
```

## Scales

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .3) +
  labs(
    title = "Temperature at three stations",
    x = "Minimum daily temp(C)",
    y = "Maximum daily temp(C)",
    caption = "Data from rnoaa package with three stations"
  ) +
  scale_x_continuous(
    breaks = c(-15, 0, 15),
    labels = c("-15C", "0C", "15C")
  ) +
  scale_y_continuous(
    trans = "sqrt",
    position = "right"
  )
```

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .3) +
  labs(
    title = "Temperature at three stations",
    x = "Minimum daily temp(C)",
    y = "Maximum daily temp(C)",
    caption = "Data from rnoaa package with three stations"
  ) +
  scale_color_hue(
    name = "Location"
  )
  scale_color_viridis_d()
```
color scale `viridis`

## Themes

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .3) +
  labs(
    title = "Temperature at three stations",
    x = "Minimum daily temp(C)",
    y = "Maximum daily temp(C)",
    caption = "Data from rnoaa package with three stations"
  ) +
  scale_color_hue(
    name = "Location"
  ) +
  scale_color_viridis_d() +
  theme_bw() +
  theme(legend.position = "bottom")
  
    
```

### `theme` functions' orders matter


```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .3) +
  labs(
    title = "Temperature at three stations",
    x = "Minimum daily temp(C)",
    y = "Maximum daily temp(C)",
    caption = "Data from rnoaa package with three stations"
  ) +
  scale_color_hue(
    name = "Location"
  ) +
  scale_color_viridis_d() +
  theme_minimal() +
  theme(legend.position = "bottom")
    
```

## `data` in geoms

```{r}
central_park <-
  weather_df %>% 
  filter(name == "CentralPark_NY")

waikiki <- 
  weather_df %>% 
  filter(name == "Waikiki_HA")

waikiki %>% 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point() +
  geom_line(data = central_park)
```


